#!/usr/bin/env python3
"""Build a shareable, self-contained Cook Report: one HTML file with an
embedded SVG chart and per-probe stats (start/peak/final temp, stall time,
stage-crossing timestamps) -- no server, no external assets, safe to email
or post anywhere.

Usage:
  report.py                     # latest cook -> cook_report.html
  report.py --cook 2 --out r.html
"""
import html as _html
import sys

import plan
import probe_names
from forecast import _FLAT, STALL_HI, STALL_LO
from history import _num, load_rows, sessions, summarize
from plot import render_svg

_STAGE_ROW_STYLE = "color:#8a7d70;font-style:italic;font-size:12px"


def _stall_minutes(sess, probe):
    """Minutes spent genuinely stalled: consecutive readings both inside the
    classic 150-175F band AND with a near-flat rate between them (same
    threshold forecast.py uses to call a live reading "stalled"). Checking
    band membership alone would count a normal climb passing through 150-175F
    as "stalled" time, which almost every cook does on the way to any higher
    target."""
    ts = [r["_ts"] for r in sess]
    temps = [_num(r.get(f"probe{probe}_temp")) for r in sess]
    total = 0.0
    for (t0, v0), (t1, v1) in zip(zip(ts, temps), zip(ts[1:], temps[1:])):
        if v0 is None or v1 is None:
            continue
        if not (STALL_LO <= v0 <= STALL_HI and STALL_LO <= v1 <= STALL_HI):
            continue
        elapsed = (t1 - t0).total_seconds() / 60
        if elapsed <= 0:
            continue
        if (v1 - v0) / elapsed < _FLAT:
            total += elapsed
    return total


def _stage_hits(sess, probe, stages):
    """[(label, temp, datetime|None)] -- when each stage was first reached."""
    hits = []
    for stemp, label in stages.get(probe, []):
        hit = next((r["_ts"] for r in sess
                    if (_num(r.get(f"probe{probe}_temp")) or -1) >= stemp), None)
        hits.append((label, stemp, hit))
    return hits


def build_report(sess, stages=None, names=None, title="Pellet Pilot cook report"):
    """Self-contained HTML string -- no external assets, safe to share.

    Deliberately omits the raw grill `thingName` (a device identifier) that
    history.summarize() carries -- this report is meant to leave the machine,
    unlike history.py's local-only CLI output.
    """
    stages = stages or {}
    names = names or {}
    s = summarize(sess)
    svg = render_svg(sess)  # whole-cook overview: grill + every probe

    rows = []
    for i, p in sorted(s["probes"].items()):
        label = _html.escape(probe_names.label(i, names))
        stall = _stall_minutes(sess, i)
        if p["target"]:
            tgt = f"{int(p['target'])}°" + (" reached" if p["reached"] else "")
        else:
            tgt = "—"
        rows.append(
            f"<tr><td>{label}</td>"
            f'<td>{int(p["start"])}°</td><td>{int(p["peak"])}°</td><td>{int(p["final"])}°</td>'
            f"<td>{tgt}</td><td>{stall:.0f} min</td></tr>"
        )
        for lbl, stemp, hit in _stage_hits(sess, i, stages):
            when = hit.strftime("%-I:%M %p") if hit else "not reached"
            rows.append(
                f'<tr style="{_STAGE_ROW_STYLE}"><td colspan="5">{label} — '
                f"{_html.escape(lbl)} ({int(stemp)}°)</td><td>{when}</td></tr>"
            )

    hrs = s["duration_min"] / 60
    esc_title = _html.escape(title)
    return f"""<!doctype html>
<meta charset="utf-8">
<title>{esc_title}</title>
<body style="margin:0;background:#0d0b09;color:#d8cbbf;font-family:ui-sans-serif,Helvetica,Arial,sans-serif;
             display:flex;justify-content:center;padding:24px 12px">
<div style="max-width:960px;width:100%">
  <h1 style="font-weight:600;margin-bottom:4px">{esc_title}</h1>
  <p style="color:#8a7d70;margin-top:0">
    {s['start']:%A, %B} {s['start'].day} &middot; started {s['start']:%-I:%M %p} &middot;
    {hrs:.1f}h cook &middot; grill peak {int(s['max_grill'] or 0)}&deg;
  </p>
  <div>{svg}</div>
  <table style="width:100%;border-collapse:collapse;margin-top:16px;font-size:14px">
    <tr style="color:#8a7d70;text-align:left">
      <th>probe</th><th>start</th><th>peak</th><th>final</th><th>target</th><th>stall time</th>
    </tr>
    {"".join(rows)}
  </table>
  <p style="color:#5a4f45;font-size:12px;margin-top:24px">
    Generated by <a href="https://github.com/ctopherwilliams/pellet-pilot" style="color:#8a7d70">Pellet Pilot</a>
    &mdash; unofficial, read-only Traeger monitoring.
  </p>
</div>
"""


def main():
    argv = sys.argv[1:]

    def opt(name, default=None):
        return argv[argv.index(name) + 1] if name in argv else default

    cook_id = int(opt("--cook")) if "--cook" in argv else None
    groups = sessions(load_rows())
    if not groups:
        sys.exit("No cook sessions found yet.")
    sess = groups[cook_id - 1] if cook_id else groups[-1]

    out = opt("--out", "cook_report.html")
    content = build_report(sess, plan.load_plan(), probe_names.load_names())
    with open(out, "w") as f:
        f.write(content)
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
